### ISSUE TITLE
Compilation fails with RTLD_NEXT error

### ISSUE THREAD

**Issue by dansimonm** [realh/roxterm#273]
Trying to compile roxterm-3.16.2 on Slackware 15.0 gives the following error:

$ mkdir build && cd build
$ cmake ..
...
$ make
...
[ 80%] Building C object src/CMakeFiles/roxterm.dir/osc52filter.c.o
/home/dan/pkg/mysbo/roxterm/roxterm-3.16.2/src/osc52filter.c: In function ‘read’:
/home/dan/pkg/mysbo/roxterm/roxterm-3.16.2/src/osc52filter.c:326:27: error: ‘RTLD_NEXT’ undeclared (first use in this function); did you mean ‘RTLD_NOW’?
  326 |         real_read = dlsym(RTLD_NEXT, "read");
      |                           ^~~~~~~~~
      |                           RTLD_NOW
/home/dan/pkg/mysbo/roxterm/roxterm-3.16.2/src/osc52filter.c:326:27: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [src/CMakeFiles/roxterm.dir/build.make:174: src/CMakeFiles/roxterm.dir/osc52filter.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: src/CMakeFiles/roxterm.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by realh** [comment]
OK. There is an alternative way to implement this feature, but it needs a little more rewriting than simply moving one line.

**Comment by realh** [comment]
Please let me know if 3.16.4 works.

**Comment by dansimonm** [comment]
The initial error is fixed now, but I get a different error:

$ make
...
[100%] Linking C executable roxterm
/usr/bin/ld: CMakeFiles/roxterm.dir/osc52filter.c.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/roxterm.dir/build.make:325: src/roxterm] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: src/CMakeFiles/roxterm.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Is this related to a faulty Makefile perhaps, similar to this:

https://stackoverflow.com/questions/63153342/cmake-undefined-reference-to-symbol-dlsymglibc-2-2-5-even-though-i-link-with

**Comment by dansimonm** [comment]
Right, we have found our problem! Thanks for your efforts :)

My suggestion is simply to wait this out. Slackware is an ultra conservative distro, so you shouldn't see this problem in many others. And I suspect that the next version of Slackware will be released relatively soon-ish. I can try to port roxterm once the next release has come out.

**Comment by egmontkob** [comment]
I don't know whether other systems supported by xfce4-terminal (*bsd? macos? hurd? musl? etc...) need `-ldl`.

**Comment by dansimonm** [comment]
3.16.6 works perfectly in Slackware 15.0! I've submitted it to slackbuilds.org, and hopefully it will be available in the repository soon. Thanks for all the support :)

**Comment by realh** [comment]
Thanks for the feedback. I can close this now.
